import React, { useState } from 'react';
import { 
  Calculator, 
  TrendingUp, 
  ShieldCheck, 
  Coins, 
  Scale, 
  Sliders, 
  CheckCircle2, 
  AlertTriangle, 
  Sparkles, 
  ArrowRight,
  HelpCircle,
  Percent,
  Calendar,
  Layers,
  Heart
} from 'lucide-react';
import { ShariahContractType } from '../types';

interface NisbahProjectionToolProps {
  onApplyToPitchDeck?: (nisbahData: any) => void;
  onOpenPaymentModal?: () => void;
}

export const NisbahProjectionTool: React.FC<NisbahProjectionToolProps> = ({
  onApplyToPitchDeck,
  onOpenPaymentModal,
}) => {
  // Input States
  const [principalAmount, setPrincipalAmount] = useState<number>(50000);
  const [contractType, setContractType] = useState<ShariahContractType>('Mudharabah');
  const [investorNisbah, setInvestorNisbah] = useState<number>(70); // 70% Investor, 30% Mudharib
  const [tenorYears, setTenorYears] = useState<number>(3);
  const [scenario, setScenario] = useState<'conservative' | 'moderate' | 'aggressive' | 'stress_test'>('moderate');
  const [deductZakat, setDeductZakat] = useState<boolean>(true);
  const [deductRiskReserve, setDeductRiskReserve] = useState<boolean>(true);
  const [showFiqhNotes, setShowFiqhNotes] = useState<boolean>(false);
  const [copiedSuccess, setCopiedSuccess] = useState<boolean>(false);

  const managerNisbah = 100 - investorNisbah;

  // Scenario baseline gross return on investment per year
  const scenarioRates = {
    conservative: { rate: 0.125, label: 'Konservatif (12.5% Margin Usaha)' },
    moderate: { rate: 0.170, label: 'Moderat (17.0% Margin Usaha)' },
    aggressive: { rate: 0.235, label: 'Agresif (23.5% Margin Usaha)' },
    stress_test: { rate: -0.045, label: 'Uji Tekan / Penurunan Pasar (-4.5%)' },
  };

  const currentRate = scenarioRates[scenario].rate;
  const isLoss = currentRate < 0;

  // Mathematical Projections
  // Annual Revenue Generated by the Invested Capital
  const annualGrossProfit = principalAmount * currentRate;
  const operationalCostRate = 0.18; // 18% cost of operations
  
  let netOperatingProfit = 0;
  let riskReserveAmount = 0;
  let zakatAmount = 0;
  let distributableProfit = 0;
  let annualInvestorShare = 0;
  let annualManagerShare = 0;
  let annualizedRoiPercent = 0;
  let totalInvestorDividend = 0;
  let projectedFinalCapitalValue = 0;

  if (!isLoss) {
    netOperatingProfit = annualGrossProfit * (1 - operationalCostRate);
    riskReserveAmount = deductRiskReserve ? netOperatingProfit * 0.02 : 0; // 2% Tabarru' reserve
    const profitAfterReserve = netOperatingProfit - riskReserveAmount;
    zakatAmount = deductZakat ? profitAfterReserve * 0.025 : 0; // 2.5% Zakat perniagaan
    distributableProfit = profitAfterReserve - zakatAmount;

    annualInvestorShare = distributableProfit * (investorNisbah / 100);
    annualManagerShare = distributableProfit * (managerNisbah / 100);
    annualizedRoiPercent = (annualInvestorShare / principalAmount) * 100;
    totalInvestorDividend = annualInvestorShare * tenorYears;
    projectedFinalCapitalValue = principalAmount + totalInvestorDividend;
  } else {
    // Loss scenario
    // Under Fiqh Mudharabah: Financial loss is borne by capital owner (up to capital invested),
    // while Mudharib loses their labor/time.
    const annualLoss = Math.abs(annualGrossProfit);
    annualInvestorShare = -annualLoss;
    annualManagerShare = 0;
    annualizedRoiPercent = -((annualLoss / principalAmount) * 100);
    totalInvestorDividend = -annualLoss * tenorYears;
    projectedFinalCapitalValue = Math.max(0, principalAmount + totalInvestorDividend);
  }

  const handleCopyProjection = () => {
    setCopiedSuccess(true);
    if (onApplyToPitchDeck) {
      onApplyToPitchDeck({
        contractType,
        investorNisbah,
        managerNisbah,
        annualizedRoiPercent: annualizedRoiPercent.toFixed(1) + '%',
        totalDividend: totalInvestorDividend,
      });
    }
    setTimeout(() => setCopiedSuccess(false), 3000);
  };

  return (
    <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-5 sm:p-7 space-y-6 shadow-xl relative overflow-hidden">
      
      {/* Background Islamic Glow */}
      <div className="absolute top-0 right-0 w-80 h-80 bg-emerald-500/5 rounded-full blur-3xl pointer-events-none" />

      {/* Header Section */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-slate-800">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-emerald-500/20 to-teal-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
            <Scale className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-base sm:text-lg font-bold text-white">
                Kalkulator Proyeksi Profit & Loss (P&L) Berbasis Nisbah Syariah
              </h3>
              <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-emerald-950 text-emerald-300 border border-emerald-800/40">
                BEBAS RIBA
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-0.5">
              Simulasi imbal hasil nyata berdasarkan nisbah bagi hasil, transparansi biaya usaha, zakat 2.5%, dan kaidah Fiqih Muamalah AAOIFI
            </p>
          </div>
        </div>

        <button
          onClick={() => setShowFiqhNotes(!showFiqhNotes)}
          className="text-xs text-emerald-400 hover:text-emerald-300 font-medium flex items-center gap-1.5 self-start sm:self-auto"
        >
          <HelpCircle className="w-4 h-4" />
          <span>{showFiqhNotes ? 'Tutup Prinsip Fiqih' : 'Prinsip Fiqih Muamalah'}</span>
        </button>
      </div>

      {/* Fiqh Explanation Accordion */}
      {showFiqhNotes && (
        <div className="p-4 bg-slate-950 border border-emerald-900/60 rounded-xl text-xs space-y-2 animate-fadeIn text-slate-300">
          <span className="font-bold text-emerald-400 block uppercase tracking-wider text-[10px]">
            Landasan Syariah Pembagian Hasil & Risiko:
          </span>
          <p className="leading-relaxed">
            1. <strong>Kaidah Al-Ghunmu bil Ghurmi</strong>: Hak atas keuntungan sejalan dengan kesediaan menanggung risiko kerugian usaha. Tidak diperbolehkan adanya penetapan bunga tetap di muka (*Fixed Interest*) karena termasuk Riba Nasi'ah.
          </p>
          <p className="leading-relaxed">
            2. <strong>Akad Mudharabah</strong>: Shahibul Maal (pemodal) dan Mudharib (pengelola) menyepakati nisbah proporsional (misal 70:30) dari keuntungan bersih riil. Bila rugi di luar kelalaian pengelola, kerugian finansial ditanggung pemodal, sedangkan pengelola rugi waktu dan tenaga.
          </p>
          <p className="leading-relaxed">
            3. <strong>Penyucian Harta (Zakat Perniagaan 2.5%)</strong>: Keuntungan yang diperoleh secara otomatis disisihkan zakat perniagaannya untuk keberkahan harta.
          </p>
        </div>
      )}

      {/* Calculator Body: 2 Columns */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left Column: Interactive Input Controls (5 Cols) */}
        <div className="lg:col-span-5 space-y-4">
          
          {/* Principal Capital Input */}
          <div>
            <div className="flex items-center justify-between text-xs mb-1.5">
              <label className="text-slate-300 font-medium">Modal Pokok Investasi (USD)</label>
              <span className="font-mono text-emerald-400 font-extrabold text-sm">
                ${principalAmount.toLocaleString()} USD
              </span>
            </div>
            <input
              type="range"
              min={5000}
              max={500000}
              step={5000}
              value={principalAmount}
              onChange={(e) => setPrincipalAmount(Number(e.target.value))}
              className="w-full accent-emerald-500 cursor-pointer h-2 bg-slate-800 rounded-lg"
            />
            <div className="flex justify-between text-[10px] text-slate-500 mt-1 font-mono">
              <span>$5,000</span>
              <span>$250,000</span>
              <span>$500,000</span>
            </div>
          </div>

          {/* Shariah Contract Type */}
          <div>
            <label className="block text-slate-300 text-xs font-medium mb-1.5">Model Akad Pembiayaan</label>
            <div className="grid grid-cols-3 gap-2 text-xs">
              <button
                type="button"
                onClick={() => setContractType('Mudharabah')}
                className={`py-2 px-2.5 rounded-xl border text-center transition ${
                  contractType === 'Mudharabah'
                    ? 'bg-emerald-950/80 border-emerald-500 text-emerald-300 font-bold shadow'
                    : 'bg-slate-950 border-slate-800 text-slate-400 hover:text-white'
                }`}
              >
                Mudharabah
              </button>
              <button
                type="button"
                onClick={() => setContractType('Musyarakah')}
                className={`py-2 px-2.5 rounded-xl border text-center transition ${
                  contractType === 'Musyarakah'
                    ? 'bg-emerald-950/80 border-emerald-500 text-emerald-300 font-bold shadow'
                    : 'bg-slate-950 border-slate-800 text-slate-400 hover:text-white'
                }`}
              >
                Musyarakah
              </button>
              <button
                type="button"
                onClick={() => setContractType('Sukuk Al-Ijarah')}
                className={`py-2 px-2.5 rounded-xl border text-center transition ${
                  contractType === 'Sukuk Al-Ijarah'
                    ? 'bg-emerald-950/80 border-emerald-500 text-emerald-300 font-bold shadow'
                    : 'bg-slate-950 border-slate-800 text-slate-400 hover:text-white'
                }`}
              >
                Sukuk Ijarah
              </button>
            </div>
          </div>

          {/* Nisbah Ratio Selector */}
          <div>
            <div className="flex items-center justify-between text-xs mb-1.5">
              <label className="text-slate-300 font-medium">
                Porsi Nisbah (Pemodal : Pengelola)
              </label>
              <span className="font-mono text-white font-bold">
                <span className="text-emerald-400">{investorNisbah}%</span> : <span className="text-teal-400">{managerNisbah}%</span>
              </span>
            </div>

            {/* Quick Nisbah Presets */}
            <div className="grid grid-cols-4 gap-1.5 text-xs mb-2">
              {[
                { inv: 60, label: '60 : 40' },
                { inv: 70, label: '70 : 30' },
                { inv: 75, label: '75 : 25' },
                { inv: 80, label: '80 : 20' },
              ].map((preset) => (
                <button
                  key={preset.inv}
                  type="button"
                  onClick={() => setInvestorNisbah(preset.inv)}
                  className={`py-1.5 rounded-lg border text-xs font-semibold transition ${
                    investorNisbah === preset.inv
                      ? 'bg-emerald-500 text-slate-950 border-emerald-400'
                      : 'bg-slate-950 border-slate-800 text-slate-400 hover:text-white'
                  }`}
                >
                  {preset.label}
                </button>
              ))}
            </div>

            <input
              type="range"
              min={50}
              max={90}
              step={5}
              value={investorNisbah}
              onChange={(e) => setInvestorNisbah(Number(e.target.value))}
              className="w-full accent-emerald-500 cursor-pointer h-2 bg-slate-800 rounded-lg"
            />
          </div>

          {/* Investment Tenor & Scenario */}
          <div className="grid grid-cols-2 gap-3 text-xs">
            <div>
              <label className="block text-slate-300 font-medium mb-1.5">Jangka Waktu (Tenor)</label>
              <select
                value={tenorYears}
                onChange={(e) => setTenorYears(Number(e.target.value))}
                className="w-full p-2.5 bg-slate-950 border border-slate-800 rounded-xl text-slate-200 focus:outline-none focus:border-emerald-500"
              >
                <option value={1}>1 Tahun</option>
                <option value={2}>2 Tahun</option>
                <option value={3}>3 Tahun</option>
                <option value={5}>5 Tahun</option>
              </select>
            </div>

            <div>
              <label className="block text-slate-300 font-medium mb-1.5">Skenario Kinerja</label>
              <select
                value={scenario}
                onChange={(e) => setScenario(e.target.value as any)}
                className="w-full p-2.5 bg-slate-950 border border-slate-800 rounded-xl text-slate-200 focus:outline-none focus:border-emerald-500 font-medium"
              >
                <option value="conservative">Konservatif (12.5%)</option>
                <option value="moderate">Moderat (17.0%)</option>
                <option value="aggressive">Agresif (23.5%)</option>
                <option value="stress_test">Uji Tekan (-4.5%)</option>
              </select>
            </div>
          </div>

          {/* Shariah Toggles (Zakat & Cadangan Tabarru') */}
          <div className="space-y-2 pt-1 border-t border-slate-800 text-xs">
            <label className="flex items-center justify-between cursor-pointer p-2 rounded-lg hover:bg-slate-950/60 transition">
              <span className="text-slate-300">Penyucian Zakat Perniagaan (2.5% otomatis)</span>
              <input
                type="checkbox"
                checked={deductZakat}
                onChange={(e) => setDeductZakat(e.target.checked)}
                className="w-4 h-4 accent-emerald-500 rounded"
              />
            </label>

            <label className="flex items-center justify-between cursor-pointer p-2 rounded-lg hover:bg-slate-950/60 transition">
              <span className="text-slate-300">Cadangan Risiko Takaful / Tabarru' (2.0%)</span>
              <input
                type="checkbox"
                checked={deductRiskReserve}
                onChange={(e) => setDeductRiskReserve(e.target.checked)}
                className="w-4 h-4 accent-emerald-500 rounded"
              />
            </label>
          </div>

        </div>

        {/* Right Column: Financial Breakdown & P&L Waterfall (7 Cols) */}
        <div className="lg:col-span-7 space-y-4">
          
          {/* Top Key Result Banner */}
          <div className={`p-5 rounded-2xl border transition-all ${
            isLoss
              ? 'bg-red-950/40 border-red-800/60'
              : 'bg-gradient-to-br from-emerald-950/50 via-slate-950 to-teal-950/40 border-emerald-800/50 shadow-lg'
          }`}>
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
              <div>
                <span className="text-xs uppercase font-semibold tracking-wider text-slate-400 block">
                  {isLoss ? 'Simulasi Uji Tekan (Absorpsi Kerugian)' : 'Estimasi Net Yield Pemodal per Tahun'}
                </span>
                <div className={`text-3xl sm:text-4xl font-black mt-1 font-mono ${
                  isLoss ? 'text-red-400' : 'text-emerald-400'
                }`}>
                  {annualizedRoiPercent >= 0 ? `+${annualizedRoiPercent.toFixed(1)}%` : `${annualizedRoiPercent.toFixed(1)}%`}
                  <span className="text-xs font-normal text-slate-400 ml-1.5 font-sans">p.a (Bersih Zakat)</span>
                </div>
              </div>

              <div className="text-right">
                <span className="text-xs text-slate-400 block">Total Dividen ({tenorYears} Tahun)</span>
                <span className={`text-xl font-bold font-mono ${isLoss ? 'text-red-400' : 'text-white'}`}>
                  {totalInvestorDividend >= 0 ? `+$${Math.round(totalInvestorDividend).toLocaleString()}` : `-$${Math.round(Math.abs(totalInvestorDividend)).toLocaleString()}`} USD
                </span>
                <div className="text-[11px] text-slate-400 mt-0.5">
                  Nilai Akhir: <strong className="text-slate-200">${Math.round(projectedFinalCapitalValue).toLocaleString()} USD</strong>
                </div>
              </div>
            </div>
          </div>

          {/* Detailed Waterfall Breakdown */}
          <div className="p-4 bg-slate-950 border border-slate-800 rounded-xl space-y-2.5 text-xs">
            <span className="font-bold text-slate-200 block uppercase tracking-wider text-[11px]">
              Aliran Distribusi Finansial Riil per Tahun ({contractType}):
            </span>

            <div className="space-y-1.5 divide-y divide-slate-900">
              
              <div className="flex justify-between py-1.5">
                <span className="text-slate-400">1. Pendapatan Usaha Bruto Terproyeksi:</span>
                <span className={`font-mono font-semibold ${annualGrossProfit >= 0 ? 'text-white' : 'text-red-400'}`}>
                  ${Math.round(annualGrossProfit).toLocaleString()} USD
                </span>
              </div>

              {!isLoss && (
                <>
                  <div className="flex justify-between py-1.5 text-slate-400">
                    <span>2. Beban Operasional Riil (18% COGS):</span>
                    <span className="font-mono text-red-400/80">
                      -${Math.round(annualGrossProfit * operationalCostRate).toLocaleString()} USD
                    </span>
                  </div>

                  <div className="flex justify-between py-1.5">
                    <span className="text-slate-300 font-medium">3. Laba Bersih Usaha (Net Operating Profit):</span>
                    <span className="font-mono text-teal-400 font-bold">
                      ${Math.round(netOperatingProfit).toLocaleString()} USD
                    </span>
                  </div>

                  {deductRiskReserve && (
                    <div className="flex justify-between py-1.5 text-slate-400">
                      <span>4. Cadangan Risiko Operasional (Tabarru' 2.0%):</span>
                      <span className="font-mono text-amber-400/80">
                        -${Math.round(riskReserveAmount).toLocaleString()} USD
                      </span>
                    </div>
                  )}

                  {deductZakat && (
                    <div className="flex justify-between py-1.5 text-slate-400">
                      <span>5. Zakat Perniagaan (2.5% disucikan):</span>
                      <span className="font-mono text-amber-400">
                        -${Math.round(zakatAmount).toLocaleString()} USD
                      </span>
                    </div>
                  )}

                  <div className="flex justify-between py-2 bg-slate-900/60 px-2 rounded-lg font-bold">
                    <span className="text-emerald-300">Bagian Shahibul Maal ({investorNisbah}%):</span>
                    <span className="font-mono text-emerald-400 text-sm">
                      +${Math.round(annualInvestorShare).toLocaleString()} USD / thn
                    </span>
                  </div>

                  <div className="flex justify-between py-1.5 px-2 text-slate-400">
                    <span>Bagian Mudharib / Pengelola ({managerNisbah}%):</span>
                    <span className="font-mono text-teal-300">
                      +${Math.round(annualManagerShare).toLocaleString()} USD / thn
                    </span>
                  </div>
                </>
              )}

              {isLoss && (
                <div className="p-3 bg-red-950/60 border border-red-900 rounded-lg text-red-300 text-[11px] leading-relaxed">
                  <div className="flex items-center gap-1.5 font-bold mb-1">
                    <AlertTriangle className="w-4 h-4 text-red-400 shrink-0" />
                    <span>Penerapan Hukum Fiqih saat Usaha Merugi:</span>
                  </div>
                  Sesuai Fatwa DSN-MUI & Standar AAOIFI No. 13: Pada akad Mudharabah, kerugian finansial diserap dari modal Shahibul Maal hingga batas modal yang disetor. Pengelola (Mudharib) tidak menerima upah manajemen dan kehilangan hasil jerih payahnya, kecuali terbukti ada kecurangan (*Ta'addi*) atau kelalaian disengaja (*Taqshir*).
                </div>
              )}

            </div>
          </div>

          {/* Action CTAs */}
          <div className="flex flex-wrap items-center justify-between gap-3 pt-1">
            <button
              onClick={handleCopyProjection}
              className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl text-xs font-semibold border border-slate-700 flex items-center gap-1.5 transition"
            >
              {copiedSuccess ? (
                <>
                  <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                  <span>Tersalin ke Pitch Deck!</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 text-emerald-400" />
                  <span>Terapkan Nisbah ke Pitch Deck</span>
                </>
              )}
            </button>

            {onOpenPaymentModal && (
              <button
                onClick={onOpenPaymentModal}
                className="px-4 py-2 bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white rounded-xl text-xs font-bold shadow-md shadow-emerald-950 flex items-center gap-1.5 transition"
              >
                <Coins className="w-4 h-4" />
                <span>Mulai Investasi dengan Skema Ini</span>
              </button>
            )}
          </div>

        </div>

      </div>

    </div>
  );
};
